### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by hs-07** [hs-07/Clock#2]
Edit the footer and make it look more attractive with hover animations and different colours on different icons.

**Comment by jeetsdev** [comment]
Hey @hs-07  , I want to work on it.

**Comment by mehraankush** [comment]
i will do that asap.. @hs-07

**Comment by nirajpdn** [comment]
As a frontend guy, i also want to contribute. Please create more issues of design & features.

**Comment by sunidhisachan** [comment]
hey @hs-07 I can try this , please assign this to me as well.

**Comment by hs-07** [comment]
@jeetsdev 
@nirajpdn 
@sunidhisachan 
@mehraankush 
I have assigned it to all. The best PR will be merged so try your level best.
Thanks for showing interest.

Fork the project, commit changes in it, and make PR.
AND Dont forget to star the repo.😊

**Comment by DHRUVKHANDELWAL00** [comment]
HEY @hs-07 , I can definitely try this out. Please assign it to me as well.

**Comment by hs-07** [comment]
Did anyone completed the task assigned ??

**Comment by DHRUVKHANDELWAL00** [comment]
hey @hs-07 , i have made chnages ...do let me know if something is missing. if no, then please accept it under hacktoberfest

**Comment by DHRUVKHANDELWAL00** [comment]
hey @hs-07 , i made the changes u asked for.... i made a new branch to change those . please check and let me know.and accept in under hacktoberfest

**Comment by hs-07** [comment]
@sunidhisachan 
@jeetsdev 
@nirajpdn 
@mehraankush 
any progress?
